### PR TITLE
Fix no file chosen place

### PR DESCRIPTION
**Pull request by adiwahyudi02**
Add some styles for wrapper div

### CODE REVIEW

**Comment by jywarren** [comment]
Hi, can you upload a screenshot and link back to the original issue, please? That helps us review! Thanks a lot!

**Comment by adiwahyudi02** [comment]
image
image

I added min-width property.

**Comment by jywarren** [comment]
Oh this looks really nice, but your PR is actually against my personal repository "jywarren" instead of against https://github.com/publiclab/image-sequencer -- would you mind closing and reopening one over there?

**Comment by adiwahyudi02** [comment]
Ops, sorry. Ok, I will reopening it over there, thanks

**Pull request closed without merging**
